name: rice_qc
description: Offline AI app to analyze rice/paddy quality (rICE qc)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  tflite_flutter: ^0.10.4
  permission_handler: ^11.3.1
  pdf: ^3.11.0
  printing: ^5.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo-aan.png
    # Drop your model file here and uncomment:
    # - assets/model/rice_qc.tflite
